# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

import os
import unittest

from azure_devtools.scenario_tests import AllowLargeResponse
from azure.cli.testsdk import ScenarioTest
from .. import try_manual
from azure.cli.testsdk import ResourceGroupPreparer


TEST_DIR = os.path.abspath(os.path.join(os.path.abspath(__file__), '..'))


@try_manual
def setup(test, rg):
    pass


# EXAMPLE: /Accounts/put/Accounts_Create
@try_manual
def step__accounts_put_accounts_create(test, rg):
    test.cmd('az datashare account create '
             '--identity type="SystemAssigned" '
             '--location "West US 2" '
             '--tags tag1="Red" tag2="White" '
             '--account-name "{Account1}" '
             '--resource-group "{rg}"',
             checks=[])


# EXAMPLE: /Shares/put/Shares_Create
@try_manual
def step__shares_put_shares_create(test, rg):
    test.cmd('az datashare create '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--description "share description" '
             '--share-kind "CopyBased" '
             '--terms "Confidential" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /DataSets/put/DataSets_SqlDWTable_Create
@try_manual
def step__datasets_put_datasets_sqldwtable_create(test, rg):
    test.cmd('az datashare data-set create '
             '--account-name "{Account1}" '
             '--sql-dw-table-data-set properties={{"dataWarehouseName":"DataWarehouse1","schemaName":"dbo","sqlServerRe'
             'sourceId":"/subscriptions/433a8dfd-e5d5-4e77-ad86-90acdc75eb1a/resourceGroups/SampleResourceGroup/provide'
             'rs/Microsoft.Sql/servers/Server1","tableName":"Table1"}} '
             '--data-set-name "{Dataset1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /DataSets/put/DataSets_SqlDBTable_Create
@try_manual
def step__datasets_put_datasets_sqldbtable_create(test, rg):
    test.cmd('az datashare data-set create '
             '--account-name "{Account1}" '
             '--sql-d-b-table-data-set properties={{"databaseName":"SqlDB1","schemaName":"dbo","sqlServerResourceId":"/'
             'subscriptions/433a8dfd-e5d5-4e77-ad86-90acdc75eb1a/resourceGroups/SampleResourceGroup/providers/Microsoft'
             '.Sql/servers/Server1","tableName":"Table1"}} '
             '--data-set-name "{Dataset1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /DataSets/put/DataSets_KustoDatabase_Create
@try_manual
def step__datasets_put_datasets_kustodatabase_create(test, rg):
    test.cmd('az datashare data-set create '
             '--account-name "{Account1}" '
             '--kusto-database-data-set properties={{"kustoDatabaseResourceId":"/subscriptions/433a8dfd-e5d5-4e77-ad86-'
             '90acdc75eb1a/resourceGroups/SampleResourceGroup/providers/Microsoft.Kusto/clusters/Cluster1/databases/Dat'
             'abase1"}} '
             '--data-set-name "{Dataset1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /DataSets/put/DataSets_KustoCluster_Create
@try_manual
def step__datasets_put_datasets_kustocluster_create(test, rg):
    test.cmd('az datashare data-set create '
             '--account-name "{Account1}" '
             '--kusto-cluster-data-set properties={{"kustoClusterResourceId":"/subscriptions/433a8dfd-e5d5-4e77-ad86-90'
             'acdc75eb1a/resourceGroups/SampleResourceGroup/providers/Microsoft.Kusto/clusters/Cluster1"}} '
             '--data-set-name "{Dataset1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /DataSets/put/DataSets_Create
@try_manual
def step__datasets_put_datasets_create(test, rg):
    test.cmd('az datashare data-set create '
             '--account-name "{Account1}" '
             '--blob-data-set properties={{"containerName":"C1","filePath":"file21","resourceGroup":"SampleResourceGrou'
             'p","storageAccountName":"storage2","subscriptionId":"433a8dfd-e5d5-4e77-ad86-90acdc75eb1a"}} '
             '--data-set-name "{Dataset1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/put/ShareSubscriptions_Create
@try_manual
def step__sharesubscriptions_put_sharesubscriptions_create(test, rg):
    test.cmd('az datashare-subscription create '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--invitation-id "12345678-1234-1234-12345678abd" '
             '--source-share-location "eastus2" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /Invitations/put/Invitations_Create
@try_manual
def step__invitations_put_invitations_create(test, rg):
    test.cmd('az datashare invitation create '
             '--account-name "{Account1}" '
             '--target-email "receiver@microsoft.com" '
             '--invitation-name "{Invitation1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /Triggers/put/Triggers_Create
@try_manual
def step__triggers_put_triggers_create(test, rg):
    test.cmd('az datashare consumer trigger create '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}" '
             '--scheduled-trigger properties={{"recurrenceInterval":"Day","synchronizationMode":"Incremental","synchron'
             'izationTime":"2018-11-14T04:47:52.9614956Z"}} '
             '--trigger-name "{Trigger1}"',
             checks=[])


# EXAMPLE: /SynchronizationSettings/put/SynchronizationSettings_Create
@try_manual
def step__synchronizationsettings_put_synchronizationsettings_create(test, rg):
    test.cmd('az datashare synchronization-setting create '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}" '
             '--scheduled-synchronization-setting properties={{"recurrenceInterval":"Day","synchronizationTime":"2018-1'
             '1-14T04:47:52.9614956Z"}} '
             '--synchronization-setting-name "{Dataset1}"',
             checks=[])


# EXAMPLE: /DataSetMappings/put/DataSetMappings_SqlDW_Create
@try_manual
def step__datasetmappings_put_datasetmappings_sqldw_create(test, rg):
    test.cmd('az datashare consumer dataset-mapping create '
             '--account-name "{Account1}" '
             '--sql-dw-table-data-set-mapping properties={{"dataSetId":"a08f184b-0567-4b11-ba22-a1199336d226","dataWare'
             'houseName":"DataWarehouse1","schemaName":"dbo","sqlServerResourceId":"/subscriptions/433a8dfd-e5d5-4e77-a'
             'd86-90acdc75eb1a/resourceGroups/SampleResourceGroup/providers/Microsoft.Sql/servers/Server1","tableName":'
             '"Table1"}} '
             '--data-set-mapping-name "{DatasetMapping1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /DataSetMappings/put/DataSetMappings_SqlDWDataSetToAdlsGen2File_Create
@try_manual
def step__datasetmappings_put_datasetmappings_sqldwdatasettoadlsgen2file_create(test, rg):
    test.cmd('az datashare consumer dataset-mapping create '
             '--account-name "{Account1}" '
             '--adls-gen2-file-data-set-mapping properties={{"dataSetId":"a08f184b-0567-4b11-ba22-a1199336d226","filePa'
             'th":"file21","fileSystem":"fileSystem","outputType":"Csv","resourceGroup":"SampleResourceGroup","storageA'
             'ccountName":"storage2","subscriptionId":"433a8dfd-e5d5-4e77-ad86-90acdc75eb1a"}} '
             '--data-set-mapping-name "{DatasetMapping1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /DataSetMappings/put/DataSetMappings_SqlDB_Create
@try_manual
def step__datasetmappings_put_datasetmappings_sqldb_create(test, rg):
    test.cmd('az datashare consumer dataset-mapping create '
             '--account-name "{Account1}" '
             '--sql-d-b-table-data-set-mapping properties={{"dataSetId":"a08f184b-0567-4b11-ba22-a1199336d226","databas'
             'eName":"Database1","schemaName":"dbo","sqlServerResourceId":"/subscriptions/433a8dfd-e5d5-4e77-ad86-90acd'
             'c75eb1a/resourceGroups/SampleResourceGroup/providers/Microsoft.Sql/servers/Server1","tableName":"Table1"}'
             '} '
             '--data-set-mapping-name "{DatasetMapping1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /DataSetMappings/put/DataSetMappings_Create
@try_manual
def step__datasetmappings_put_datasetmappings_create(test, rg):
    test.cmd('az datashare consumer dataset-mapping create '
             '--account-name "{Account1}" '
             '--blob-data-set-mapping properties={{"containerName":"C1","dataSetId":"a08f184b-0567-4b11-ba22-a1199336d2'
             '26","filePath":"file21","resourceGroup":"SampleResourceGroup","storageAccountName":"storage2","subscripti'
             'onId":"433a8dfd-e5d5-4e77-ad86-90acdc75eb1a"}} '
             '--data-set-mapping-name "{DatasetMapping1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /DataSetMappings/get/DataSetMappings_Get
@try_manual
def step__datasetmappings_get_datasetmappings_get(test, rg):
    test.cmd('az datashare consumer dataset-mapping show '
             '--account-name "{Account1}" '
             '--data-set-mapping-name "{DatasetMapping1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /ProviderShareSubscriptions/get/ProviderShareSubscriptions_GetByShare
@try_manual
def step__providersharesubscriptions_get_providersharesubscriptions_getbyshare(test, rg):
    test.cmd('az datashare provider-share-subscription show '
             '--account-name "{Account1}" '
             '--provider-share-subscription-id "d5496da4-9c52-402f-b067-83cc9ddea888" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /SynchronizationSettings/get/SynchronizationSettings_Get
@try_manual
def step__synchronizationsettings_get_synchronizationsettings_get(test, rg):
    test.cmd('az datashare synchronization-setting show '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}" '
             '--synchronization-setting-name "{SynchronizationSettings_2}"',
             checks=[])


# EXAMPLE: /Triggers/get/Triggers_Get
@try_manual
def step__triggers_get_triggers_get(test, rg):
    test.cmd('az datashare consumer trigger show '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}" '
             '--trigger-name "{Trigger1}"',
             checks=[])


# EXAMPLE: /Invitations/get/Invitations_Get
@try_manual
def step__invitations_get_invitations_get(test, rg):
    test.cmd('az datashare invitation show '
             '--account-name "{Account1}" '
             '--invitation-name "{Invitation1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/get/ShareSubscriptions_Get
@try_manual
def step__sharesubscriptions_get_sharesubscriptions_get(test, rg):
    test.cmd('az datashare-subscription show '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /DataSets/get/DataSets_Get
@try_manual
def step__datasets_get_datasets_get(test, rg):
    test.cmd('az datashare data-set show '
             '--account-name "{Account1}" '
             '--data-set-name "{Dataset1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /Shares/get/Shares_Get
@try_manual
def step__shares_get_shares_get(test, rg):
    test.cmd('az datashare show '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /Accounts/get/Accounts_Get
@try_manual
def step__accounts_get_accounts_get(test, rg):
    test.cmd('az datashare account show '
             '--account-name "{Account1}" '
             '--resource-group "{rg}"',
             checks=[])


# EXAMPLE: /ConsumerInvitations/get/ConsumerInvitations_Get
@try_manual
def step__consumerinvitations_get_consumerinvitations_get(test, rg):
    test.cmd('az datashare consumer invitation show '
             '--invitation-id "dfbbc788-19eb-4607-a5a1-c74181bfff03" '
             '--location "East US 2"',
             checks=[])


# EXAMPLE: /ConsumerSourceDataSets/get/ConsumerSourceDataSets_ListByShareSubscription
@try_manual
def step__consumersourcedatasets_get_consumersourcedatasets_listbysharesubscription(test, rg):
    test.cmd('az datashare consumer share-subscription list-source-dataset list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscriptions_2}"',
             checks=[])


# EXAMPLE: /DataSetMappings/get/DataSetMappings_ListByShareSubscription
@try_manual
def step__datasetmappings_get_datasetmappings_listbysharesubscription(test, rg):
    test.cmd('az datashare consumer dataset-mapping list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /Triggers/get/Triggers_ListByShareSubscription
@try_manual
def step__triggers_get_triggers_listbysharesubscription(test, rg):
    test.cmd('az datashare consumer trigger list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /ProviderShareSubscriptions/get/ProviderShareSubscriptions_ListByShare
@try_manual
def step__providersharesubscriptions_get_providersharesubscriptions_listbyshare(test, rg):
    test.cmd('az datashare provider-share-subscription list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /SynchronizationSettings/get/SynchronizationSettings_ListByShare
@try_manual
def step__synchronizationsettings_get_synchronizationsettings_listbyshare(test, rg):
    test.cmd('az datashare synchronization-setting list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /Invitations/get/Invitations_ListByShare
@try_manual
def step__invitations_get_invitations_listbyshare(test, rg):
    test.cmd('az datashare invitation list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /DataSets/get/DataSets_ListByShare
@try_manual
def step__datasets_get_datasets_listbyshare(test, rg):
    test.cmd('az datashare data-set list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/get/ShareSubscriptions_ListByAccount
@try_manual
def step__sharesubscriptions_get_sharesubscriptions_listbyaccount(test, rg):
    test.cmd('az datashare-subscription list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}"',
             checks=[])


# EXAMPLE: /Shares/get/Shares_ListByAccount
@try_manual
def step__shares_get_shares_listbyaccount(test, rg):
    test.cmd('az datashare list '
             '--account-name "{Account1}" '
             '--resource-group "{rg}"',
             checks=[])


# EXAMPLE: /Accounts/get/Accounts_ListByResourceGroup
@try_manual
def step__accounts_get_accounts_listbyresourcegroup(test, rg):
    test.cmd('az datashare account list '
             '--resource-group "{rg}"',
             checks=[])


# EXAMPLE: /Accounts/get/Accounts_ListBySubscription
@try_manual
def step__accounts_get_accounts_listbysubscription(test, rg):
    test.cmd('az datashare account list',
             checks=[])


# EXAMPLE: /ProviderShareSubscriptions/post/ProviderShareSubscriptions_Reinstate
@try_manual
def step__providersharesubscriptions_post_providersharesubscriptions_reinstate(test, rg):
    test.cmd('az datashare provider-share-subscription reinstate '
             '--account-name "{Account1}" '
             '--provider-share-subscription-id "d5496da4-9c52-402f-b067-83cc9ddea888" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /ProviderShareSubscriptions/post/ProviderShareSubscriptions_Revoke
@try_manual
def step__providersharesubscriptions_post_providersharesubscriptions_revoke(test, rg):
    test.cmd('az datashare provider-share-subscription revoke '
             '--account-name "{Account1}" '
             '--provider-share-subscription-id "d5496da4-9c52-402f-b067-83cc9ddea888" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/post/ShareSubscriptions_ListSourceShareSynchronizationSettings
@try_manual
def step__sharesubscriptions_post_sharesubscriptions_listsourcesharesynchronizationsettings(test, rg):
    test.cmd('az datashare-subscription list-source-share-synchronization-setting '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscriptions_3}"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/post/ShareSubscriptions_ListSynchronizationDetails
@try_manual
def step__sharesubscriptions_post_sharesubscriptions_listsynchronizationdetails(test, rg):
    test.cmd('az datashare-subscription list-synchronization-detail '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscriptions_3}" '
             '--synchronization-id "7d0536a6-3fa5-43de-b152-3d07c4f6b2bb"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/post/ShareSubscriptions_CancelSynchronization
@try_manual
def step__sharesubscriptions_post_sharesubscriptions_cancelsynchronization(test, rg):
    test.cmd('az datashare-subscription cancel-synchronization '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}" '
             '--synchronization-id "7d0536a6-3fa5-43de-b152-3d07c4f6b2bb"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/post/ShareSubscriptions_ListSynchronizations
@try_manual
def step__sharesubscriptions_post_sharesubscriptions_listsynchronizations(test, rg):
    test.cmd('az datashare-subscription list-synchronization '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscriptions_3}"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/post/ShareSubscriptions_Synchronize
@try_manual
def step__sharesubscriptions_post_sharesubscriptions_synchronize(test, rg):
    test.cmd('az datashare-subscription synchronize '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}" '
             '--synchronization-mode "Incremental"',
             checks=[])


# EXAMPLE: /Shares/post/Shares_ListSynchronizationDetails
@try_manual
def step__shares_post_shares_listsynchronizationdetails(test, rg):
    test.cmd('az datashare list-synchronization-detail '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}" '
             '--synchronization-id "7d0536a6-3fa5-43de-b152-3d07c4f6b2bb"',
             checks=[])


# EXAMPLE: /Shares/post/Shares_ListSynchronizations
@try_manual
def step__shares_post_shares_listsynchronizations(test, rg):
    test.cmd('az datashare list-synchronization '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /Accounts/patch/Accounts_Update
@try_manual
def step__accounts_patch_accounts_update(test, rg):
    test.cmd('az datashare account update '
             '--account-name "{Account1}" '
             '--tags tag1="Red" tag2="White" '
             '--resource-group "{rg}"',
             checks=[])


# EXAMPLE: /ConsumerInvitations/post/ConsumerInvitations_RejectInvitation
@try_manual
def step__consumerinvitations_post_consumerinvitations_rejectinvitation(test, rg):
    test.cmd('az datashare consumer invitation reject-invitation '
             '--invitation-id "dfbbc788-19eb-4607-a5a1-c74181bfff03" '
             '--location "East US 2"',
             checks=[])


# EXAMPLE: /ConsumerInvitations/get/ConsumerInvitations_ListInvitations
@try_manual
def step__consumerinvitations_get_consumerinvitations_listinvitations(test, rg):
    test.cmd('az datashare consumer invitation list-invitation',
             checks=[])


# EXAMPLE: /DataSetMappings/delete/DataSetMappings_Delete
@try_manual
def step__datasetmappings_delete_datasetmappings_delete(test, rg):
    test.cmd('az datashare consumer dataset-mapping delete '
             '--account-name "{Account1}" '
             '--data-set-mapping-name "{DatasetMapping1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /SynchronizationSettings/delete/SynchronizationSettings_Delete
@try_manual
def step__synchronizationsettings_delete_synchronizationsettings_delete(test, rg):
    test.cmd('az datashare synchronization-setting delete '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}" '
             '--synchronization-setting-name "{SynchronizationSettings_2}"',
             checks=[])


# EXAMPLE: /Triggers/delete/Triggers_Delete
@try_manual
def step__triggers_delete_triggers_delete(test, rg):
    test.cmd('az datashare consumer trigger delete '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}" '
             '--trigger-name "{Trigger1}"',
             checks=[])


# EXAMPLE: /Invitations/delete/Invitations_Delete
@try_manual
def step__invitations_delete_invitations_delete(test, rg):
    test.cmd('az datashare invitation delete '
             '--account-name "{Account1}" '
             '--invitation-name "{Invitation1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /ShareSubscriptions/delete/ShareSubscriptions_Delete
@try_manual
def step__sharesubscriptions_delete_sharesubscriptions_delete(test, rg):
    test.cmd('az datashare-subscription delete '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-subscription-name "{ShareSubscription1}"',
             checks=[])


# EXAMPLE: /DataSets/delete/DataSets_Delete
@try_manual
def step__datasets_delete_datasets_delete(test, rg):
    test.cmd('az datashare data-set delete '
             '--account-name "{Account1}" '
             '--data-set-name "{Dataset1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /Shares/delete/Shares_Delete
@try_manual
def step__shares_delete_shares_delete(test, rg):
    test.cmd('az datashare delete '
             '--account-name "{Account1}" '
             '--resource-group "{rg}" '
             '--share-name "{Share1}"',
             checks=[])


# EXAMPLE: /Accounts/delete/Accounts_Delete
@try_manual
def step__accounts_delete_accounts_delete(test, rg):
    test.cmd('az datashare account delete '
             '--account-name "{Account1}" '
             '--resource-group "{rg}"',
             checks=[])


@try_manual
def cleanup(test, rg):
    pass


class DataShareManagementClientScenarioTest(ScenarioTest):

    @ResourceGroupPreparer(name_prefix='clitestdatashare_SampleResourceGroup'[:7], key='rg', parameter_name='rg')
    def test_datashare(self, rg):

        self.kwargs.update({
            'Account1': self.create_random_name(prefix='clitestaccounts'[:7], length=24),
            'Share1': self.create_random_name(prefix='clitestshares'[:7], length=24),
            'ShareSubscription1': self.create_random_name(prefix='clitestshare_subscriptions'[:7], length=24),
            'ShareSubscriptions_2': 'ShareSubscriptions_2',
            'ShareSubscriptions_3': 'ShareSubscriptions_3',
            'Dataset1': self.create_random_name(prefix='clitestsynchronization_settings'[:7], length=24),
            'SynchronizationSettings_2': 'SynchronizationSettings_2',
            'Trigger1': self.create_random_name(prefix='clitesttriggers'[:7], length=24),
            'Dataset1': self.create_random_name(prefix='clitestdata_sets'[:7], length=24),
            'DatasetMapping1': self.create_random_name(prefix='clitestdata_set_mappings'[:7], length=24),
            'Invitation1': self.create_random_name(prefix='clitestinvitations'[:7], length=24),
        })

        setup(self, rg)
        step__accounts_put_accounts_create(self, rg)
        step__shares_put_shares_create(self, rg)
        step__datasets_put_datasets_sqldwtable_create(self, rg)
        step__datasets_put_datasets_sqldbtable_create(self, rg)
        step__datasets_put_datasets_kustodatabase_create(self, rg)
        step__datasets_put_datasets_kustocluster_create(self, rg)
        step__datasets_put_datasets_create(self, rg)
        step__sharesubscriptions_put_sharesubscriptions_create(self, rg)
        step__invitations_put_invitations_create(self, rg)
        step__triggers_put_triggers_create(self, rg)
        step__synchronizationsettings_put_synchronizationsettings_create(self, rg)
        step__datasetmappings_put_datasetmappings_sqldw_create(self, rg)
        step__datasetmappings_put_datasetmappings_sqldwdatasettoadlsgen2file_create(self, rg)
        step__datasetmappings_put_datasetmappings_sqldb_create(self, rg)
        step__datasetmappings_put_datasetmappings_create(self, rg)
        step__datasetmappings_get_datasetmappings_get(self, rg)
        step__providersharesubscriptions_get_providersharesubscriptions_getbyshare(self, rg)
        step__synchronizationsettings_get_synchronizationsettings_get(self, rg)
        step__triggers_get_triggers_get(self, rg)
        step__invitations_get_invitations_get(self, rg)
        step__sharesubscriptions_get_sharesubscriptions_get(self, rg)
        step__datasets_get_datasets_get(self, rg)
        step__shares_get_shares_get(self, rg)
        step__accounts_get_accounts_get(self, rg)
        step__consumerinvitations_get_consumerinvitations_get(self, rg)
        step__consumersourcedatasets_get_consumersourcedatasets_listbysharesubscription(self, rg)
        step__datasetmappings_get_datasetmappings_listbysharesubscription(self, rg)
        step__triggers_get_triggers_listbysharesubscription(self, rg)
        step__providersharesubscriptions_get_providersharesubscriptions_listbyshare(self, rg)
        step__synchronizationsettings_get_synchronizationsettings_listbyshare(self, rg)
        step__invitations_get_invitations_listbyshare(self, rg)
        step__datasets_get_datasets_listbyshare(self, rg)
        step__sharesubscriptions_get_sharesubscriptions_listbyaccount(self, rg)
        step__shares_get_shares_listbyaccount(self, rg)
        step__accounts_get_accounts_listbyresourcegroup(self, rg)
        step__accounts_get_accounts_listbysubscription(self, rg)
        step__providersharesubscriptions_post_providersharesubscriptions_reinstate(self, rg)
        step__providersharesubscriptions_post_providersharesubscriptions_revoke(self, rg)
        step__sharesubscriptions_post_sharesubscriptions_listsourcesharesynchronizationsettings(self, rg)
        step__sharesubscriptions_post_sharesubscriptions_listsynchronizationdetails(self, rg)
        step__sharesubscriptions_post_sharesubscriptions_cancelsynchronization(self, rg)
        step__sharesubscriptions_post_sharesubscriptions_listsynchronizations(self, rg)
        step__sharesubscriptions_post_sharesubscriptions_synchronize(self, rg)
        step__shares_post_shares_listsynchronizationdetails(self, rg)
        step__shares_post_shares_listsynchronizations(self, rg)
        step__accounts_patch_accounts_update(self, rg)
        step__consumerinvitations_post_consumerinvitations_rejectinvitation(self, rg)
        step__consumerinvitations_get_consumerinvitations_listinvitations(self, rg)
        step__datasetmappings_delete_datasetmappings_delete(self, rg)
        step__synchronizationsettings_delete_synchronizationsettings_delete(self, rg)
        step__triggers_delete_triggers_delete(self, rg)
        step__invitations_delete_invitations_delete(self, rg)
        step__sharesubscriptions_delete_sharesubscriptions_delete(self, rg)
        step__datasets_delete_datasets_delete(self, rg)
        step__shares_delete_shares_delete(self, rg)
        step__accounts_delete_accounts_delete(self, rg)
        cleanup(self, rg)
